const htmlContent = (user, url) => {
    return (
        `
        <html>
                <head>
                    <style>
                        /* Add your CSS styles here */
                        body {
                            font-family: Arial, sans-serif;
                            margin: 0;
                            padding: 0;
                            background-color: #f4f4f4;
                        }
                        .container {
                            max-width: 600px;
                            margin: 0 auto;
                            padding: 20px;
                            background-color: #ffffff;
                            border-radius: 5px;
                            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
                        }
                        .header {
                            background-color: #007bff;
                            color: #ffffff;
                            text-align: center;
                            padding: 20px 0;
                            border-top-left-radius: 5px;
                            border-top-right-radius: 5px;
                        }
                        .content {
                            padding: 20px;
                        }
                        .footer {
                            text-align: center;
                            padding: 20px 0;
                            background-color: #f4f4f4;
                            border-bottom-left-radius: 5px;
                            border-bottom-right-radius: 5px;
                        }
                    </style>
                </head>
                <body>
                    <div class="container">
                        <div class="header">
                            <h2>Reset Your Password</h2>
                        </div>
                        <div class="content">
                            <p>Hello ${user.name},</p>
                            <p>We received a request to reset your password for your account (${user.email}).</p>
                            <p>Click the link below to reset your password:</p>
                            <p><a href="${url}">Reset Password</a></p>
                            <p>If you did not initiate this request, you can safely ignore this email.</p>
                        </div>
                        <div class="footer">
                            <p>This email is autogenerated and do not reply to this.</p>
                        </div>
                    </div>
                </body>
            </html>
        `
    )
} 

module.exports = htmlContent;